<?php
// $Id$

/**
 * @file
 * Example module to demonstrate using the menu system.
 * 
 * For more information about hook_menu(), see:
 * http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_menu/7
 *
 * In this file, we are demonstrating how hook_menu() works, and how to add a simple
 * page.
 */

/**
 * Implements hook_menu().
 */
function pages_menu() {
  $items['pages'] = array(
    'title' => 'Menu system examples',
    'description' => 'Menu system example that returns a string.',
    'page callback' => 'pages_string',
    'access callback' => TRUE,
  );

  return $items;
}


/**
 * Menu callback; page callback returning a simple string.
 */
function pages_string() {
  $output = '
    <p>Pages can be returned as strings.</p>
    <p>Pages can be returned as <em>render arrays</em>.</p>';
  $output .= theme('item_list', array(
    'title' => 'Render arrays are better because...',
    'items' => array(
      'They allow content to be modified as an array.',
      'Arrays are a lot easier to modify than HTML.',
    ))
  );

  return $output;
}